id: P004264
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:52.603180
source_metadata:
  id: bdr:W1KG3412
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་ཉི་མའི་འོད་ཟེར་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  volumes:
    6df2885d35004a9ebf56a0880cd914ae:
      image_group_id: I1KG3506
      title: ''
      volume_number: 1
      total_pages: 2034
      base_file: v001.txt
    b8bb3912382b42a083e3cd291e23d1fd:
      image_group_id: I1KG3507
      title: ''
      volume_number: 2
      total_pages: 1096
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
