id: I7F1F7FF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:10:12+00:00'
last_modified: '2022-06-07T21:31:27.327565+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3412
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་ཉི་མའི་འོད་ཟེར་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1994':
      image_group_id: I1KG3506
      title: ''
      total_pages: 2034
      order: 1
      base_file: 1994.txt
    7F0A:
      image_group_id: I1KG3507
      title: ''
      total_pages: 1096
      order: 2
      base_file: 7F0A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
